# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('picture', 'picture'), ('voice', 'voice')], max_length=10)),
                ('media', models.FileField(upload_to='prompts/%Y/%m/')),
                ('caption_en', models.CharField(blank=True, help_text='English gloss shown alongside a picture.', max_length=160)),
                ('caption_ps', models.CharField(blank=True, help_text='Optional Pashto text (e.g. what the voice note says).', max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('served_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
