# Generated by Django 5.2.17 on 2026-09-07 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_raw', models.CharField(max_length=200)),
                ('text_norm', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, null=True, upload_to='contributions/%Y/%m/')),
                ('district', models.JSONField(blank=True, null=True)),
                ('tribe_path', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='corpus.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('prompt', 'contributor'), name='one_answer_per_prompt')],
            },
        ),
    ]
