# Generated by Django 5.2.17 on 2026-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='licence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prompt',
            name='media_url',
            field=models.URLField(blank=True, help_text='External media URL (e.g. Wikimedia Commons) instead of an upload.', max_length=500),
        ),
        migrations.AddField(
            model_name='prompt',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='prompts/%Y/%m/'),
        ),
    ]
