# Generated by Django 5.2.17 on 2026-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_mediablob_prompt_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='kind',
            field=models.CharField(choices=[('picture', 'picture'), ('scene', 'scene'), ('voice', 'voice')], max_length=10),
        ),
    ]
