# Generated by Django 5.2.17 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.JSONField(blank=True, help_text='Diaspora only: the country lived in now; origin stays in country/province/district.', null=True),
        ),
    ]
