# Generated by Django 5.2.17 on 2026-09-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_mediablob_prompt_blob'),
        ('identity', '0002_profile_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_blob',
            field=models.ForeignKey(blank=True, help_text='Profile photo, stored in the database so it survives redeploys.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='corpus.mediablob'),
        ),
    ]
