# Generated by Django 5.2.17 on 2026-09-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='ref.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('language', models.CharField(blank=True, max_length=120)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ref.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.SlugField(max_length=160, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='ref.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.SlugField(max_length=220, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('level', models.PositiveSmallIntegerField()),
                ('level_name', models.CharField(max_length=40)),
                ('pashto', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(max_length=40)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ref.tribe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TribeDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dominant', 'dominant'), ('present', 'present')], max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribe_links', to='ref.district')),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_links', to='ref.tribe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tribe', 'district'), name='unique_tribe_district')],
            },
        ),
    ]
