# Generated by Django 5.2.17 on 2026-09-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('province', 'province'), ('district', 'district'), ('tehsil', 'tehsil'), ('tribe', 'tribe')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160)),
                ('parent_id', models.CharField(blank=True, max_length=220)),
                ('parent_name', models.CharField(blank=True, max_length=160)),
                ('times_suggested', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('merged', 'merged'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('resolved_ref_id', models.CharField(blank=True, max_length=220)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_into', models.ForeignKey(blank=True, help_text='For the merge action: the existing tribe this duplicates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ref.tribe')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'normalized_name', 'parent_id'), name='unique_suggestion_per_parent')],
            },
        ),
    ]
