# Generated by Django 5.2.17 on 2026-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='kind',
            field=models.CharField(choices=[('province', 'province'), ('district', 'district'), ('tehsil', 'tehsil'), ('tribe', 'tribe'), ('language', 'language')], max_length=20),
        ),
    ]
