# Generated by Django 5.2.17 on 2026-09-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0003_language_alter_suggestion_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='pashto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='province',
            name='pashto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='pashto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='TribeProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribe_links', to='ref.province')),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_links', to='ref.tribe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tribe', 'province'), name='unique_tribe_province')],
            },
        ),
    ]
