# Generated by Django 5.2.17 on 2026-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_district_pashto_province_pashto_tehsil_pashto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='pashto',
            field=models.CharField(blank=True, help_text='The same name written in Pashto, when the contributor gave it.', max_length=160),
        ),
    ]
