# Generated by Django 5.2.17 on 2026-09-07 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('scope_type', models.CharField(choices=[('all', 'everyone'), ('district', 'district'), ('province', 'province')], default='all', max_length=10)),
                ('scope_id', models.CharField(blank=True, help_text='Ref id (e.g. pk-kp-khyber) when scoped.', max_length=120)),
                ('scope_name', models.CharField(blank=True, max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ends_at'],
            },
        ),
    ]
